#include "item_list.hpp"
#include "logic.hpp"
#include "rnd/item_override.h"
#include <array>
using namespace Logic;
using namespace std;
using namespace rnd;
static std::array<Item, KEY_ENUM_MAX> itemTable;

void ItemTable_Init() {    //repeatable denotes that an item in a vanilla playthrough can be obtained again after resetting time
    //Item(0, 0, "test", "test", Region::region, hint, 0, ItemCategory::Misc, LocationCategory::test, );
    //itemTable[EXAMPLE] =                        Item(advancement, repeatable,    logicVar,                         {English name     				         French          					              Spanish},                                             HintKey,               GetItemIndexValue,                  item type);
    itemTable[TEST] = Item();
    itemTable[NONE]                          = Item(false, false, &noVariable,              Text{"No Item",                      "Rien",                                            "Sin Objeto"},                                      NONE,                         (u32)GetItemID::GI_NONE,                    ITEMTYPE_EVENT);
    itemTable[KOKIRI_SWORD]                  = Item(true,  false, &KokiriSword,             Text{"Kokiri Sword",                 "Épée Kokiri",                                     "Espada Kokiri"},                                   KOKIRI_SWORD,                 (u32)GetItemID::GI_KOKIRI_SWORD,            ITEMTYPE_ITEM);
    itemTable[GREAT_FAIRYS_SWORD]            = Item(true,  false, &GreatFairySword,         Text{"Great Fairy's Sword",          "Grande Épée de Fées",                             "Espada de la Gran Hada"},                          GREAT_FAIRYS_SWORD,           (u32)GetItemID::GI_GREAT_FAIRY_SWORD,       ITEMTYPE_GFAIRY);
    itemTable[HEROS_SHIELD]                  = Item(false, false, &HerosShield,             Text{"Heros Shield",                 "Bouclier du Héros",                               "Escudo del Héroe"},                                HEROS_SHIELD,                 (u32)GetItemID::GI_SHIELD_HERO,             ITEMTYPE_ITEM);
    itemTable[DEKU_STICK]                    = Item(true,  false, &DekuStick,               Text{"Deku Stick",                   "Bâton Mojo",                                      "Palo deku"},                                       DEKU_STICK,                   (u32)GetItemID::GI_STICKS_1,                ITEMTYPE_ITEM);
    itemTable[LAND_TITLE]                    = Item(true,  true,  &LandTitle,               Text{"Land Title Deed",              "Titre de terre",                                  "Escritura de propiedad de la Ciudad"},             LAND_TITLE,                   (u32)GetItemID::GI_TOWN_TITLE_DEED,         ITEMTYPE_TRADE);
    itemTable[SWAMP_TITLE]                   = Item(true,  true,  &SwampTitle,              Text{"Swamp Title Deed",             "Titre de marais",                                 "Escritura de propiedad del Pantano"},              SWAMP_TITLE,                  (u32)GetItemID::GI_SWAMP_TITLE_DEED,        ITEMTYPE_TRADE);
    itemTable[MOUNTAIN_TITLE]                = Item(true,  true,  &MountainTitle,           Text{"Mountain Title Deed",          "Titre de montagne",                               "Escritura de propiedad de la Montañaa"},           MOUNTAIN_TITLE,               (u32)GetItemID::GI_MOUNTAIN_TITLE_DEED,     ITEMTYPE_TRADE);
    itemTable[OCEAN_TITLE]                   = Item(true,  true,  &OceanTitle,              Text{"Ocean Title Deed",             "Titre d'océan",                                   "Escritura de propiedad del Océano"},               OCEAN_TITLE,                  (u32)GetItemID::GI_OCEAN_TITLE_DEED,        ITEMTYPE_TRADE);
    itemTable[BOMBERS_NOTEBOOK]              = Item(true,  false, &BombersNotebook,         Text{"Bomber's Notebook",            "Journal des Bombers",                             "Cuaderno de los Bomber"},                          BOMBERS_NOTEBOOK,             (u32)GetItemID::GI_BOMBERS_NOTEBOOK,        ITEMTYPE_ITEM);
    itemTable[ROOM_KEY]                      = Item(true,  true,  &RoomKey,                 Text{"Room Key",                     "Clé de chambre",                                  "Llave del cuarto"},                                ROOM_KEY,                     (u32)GetItemID::GI_ROOM_KEY,                ITEMTYPE_QUEST);
    itemTable[LETTER_KAFEI]                  = Item(true,  true,  &LetterKafei,             Text{"Letter to Kafei",              "Lettre pour Kafei",                               "Carta a Kafei"},                                   LETTER_KAFEI,                 (u32)GetItemID::GI_LETTER_TO_KAFEI,         ITEMTYPE_QUEST);
    itemTable[PENDANT_MEMORIES]              = Item(true,  true,  &PendantAccess,           Text{"Pendant of Memories",          "Pendentif des amoureux",                          "Colgante de recuerdos"},                           PENDANT_MEMORIES,             (u32)GetItemID::GI_PENDANT_OF_MEMORIES,     ITEMTYPE_QUEST);
    itemTable[LETTER_MAMA]                   = Item(true,  true,  &LetterMama,              Text{"Special Delivery to Mama",     "Lettre express pour maman",                       "Entrega especial a mamá"},                         LETTER_MAMA,                  (u32)GetItemID::GI_LETTER_TO_MAMA,          ITEMTYPE_QUEST);
    itemTable[MOONS_TEAR]                    = Item(true,  true,  &MoonsTear,               Text{"Moon's Tear",                  "Larme de lune",                                   "Lágrima de luna"},                                 MOONS_TEAR,                   (u32)GetItemID::GI_MOONS_TEAR,              ITEMTYPE_TRADE);
    itemTable[SPIN_ATTACK]                   = Item(true,  false, &SpinAttack,              Text{"Spin Attack",                  "Attaque circulaire",                              "Ataque giratorio"},                                SPIN_ATTACK,                  0x2C,                                       ITEMTYPE_GFAIRY);
    itemTable[LENS_OF_TRUTH]                 = Item(true,  false, &LensOfTruth,             Text{"Lens of Truth",                "Monocle de Vérité",                               "Lupa de la Verdad"},                               LENS_OF_TRUTH,                (u32)GetItemID::GI_LENS_OF_TRUTH,           ITEMTYPE_ITEM);
    itemTable[HEROS_BOW]                     = Item(true,  false, &HerosBow,                Text{"Hero's Bow",                   "Arc du Héros",                                    "Arco del héroe"},                                  HEROS_BOW,                    (u32)GetItemID::GI_HEROS_BOW,               ITEMTYPE_ITEM);
    itemTable[FIRE_ARROWS]                   = Item(true,  false, &FireArrows,              Text{"Fire Arrow",                   "Flèche de feu",                                   "Flecha de fuego"},                                 FIRE_ARROWS,                  (u32)GetItemID::GI_FIRE_ARROW,              ITEMTYPE_ITEM);
    itemTable[ICE_ARROWS]                    = Item(true,  false, &IceArrows,               Text{"Ice Arrow",                    "Flèche de glace",                                 "Flecha de hielo"},                                 ICE_ARROWS,                   (u32)GetItemID::GI_ICE_ARROW,               ITEMTYPE_ITEM);
    itemTable[LIGHT_ARROWS]                  = Item(true,  false, &LightArrows,             Text{"Light Arrow",                  "Flèche de lumière",                               "Flecha de luz"},                                   LIGHT_ARROWS,                 (u32)GetItemID::GI_LIGHT_ARROW,             ITEMTYPE_ITEM);
    itemTable[HOOKSHOT]                      = Item(true,  false, &Hookshot,                Text{"Hookshot",                     "Grappin",                                         "Gancho"},                                          HOOKSHOT,                     (u32)GetItemID::GI_HOOKSHOT,                ITEMTYPE_ITEM);
    itemTable[MAGIC_BEAN]                    = Item(true,  false, &MagicBean,               Text{"Magic Bean",                   "Haricot magique",                                 "Habichuelas mágicas"},                             MAGIC_BEAN,                   (u32)GetItemID::GI_MAGIC_BEAN,              ITEMTYPE_ITEM);
    itemTable[MAGIC_BEAN_PACK]               = Item(true,  false, &MagicBeanPack,           Text{"Magic Bean Pack",              "Paquet de haricots magiques",                     "Lote de habichuelas mágicas"},                     MAGIC_BEAN_PACK,              (u32)GetItemID::GI_MAGIC_BEAN,              ITEMTYPE_ITEM);
    itemTable[DOUBLE_DEFENSE]                = Item(true,  false, &noVariable,              Text{"Double Defense",               "Résistance Double",                               "Poder defensivo doble"},                           DOUBLE_DEFENSE,               0xB2,                                       ITEMTYPE_GFAIRY);
    itemTable[OCARINA_OF_TIME]               = Item(true,  false, &Ocarina,                 Text{"Ocarina of Time",              "Ocarina du temps",                                "Ocarina del Tiempo"},                              OCARINA_OF_TIME,              (u32)GetItemID::GI_OCARINA_OF_TIME,         ITEMTYPE_ITEM);
    itemTable[PICTOGRAPH_BOX]                = Item(true,  false, &Pictobox,                Text{"Pictograph Box",               "Boite à Image",                                   "Caja Luminográfica"},                              PICTOGRAPH_BOX,               (u32)GetItemID::GI_PICTOGRAPH_BOX,          ITEMTYPE_ITEM);
    itemTable[POWDER_KEG]                    = Item(true,  false, &PowderKeg,               Text{"Powder Keg",                   "Baril de Poudre",                                 "Barril de Pólvora"},                               POWDER_KEG,                   (u32)GetItemID::GI_POWDER_KEG,              ITEMTYPE_ITEM);
    itemTable[KEATON_MASK]                   = Item(true,  false, &KeatonMask,              Text{"Keaton Mask",                  "Masque de renard",                                "Máscara Keaton"},                                  KEATON_MASK,                  (u32)GetItemID::GI_MASK_KEATON,             ITEMTYPE_MASK);
    itemTable[BUNNY_HOOD]                    = Item(true,  false, &BunnyHood,               Text{"Bunny Hood",                   "Masque du lapin",                                 "Capucha de conejo"},                               BUNNY_HOOD,                   (u32)GetItemID::GI_MASK_BUNNY_HOOD,         ITEMTYPE_MASK);
    itemTable[GORON_MASK]                    = Item(true,  false, &GoronMask,               Text{"Goron Mask",                   "Masque Goron",                                    "Máscara Goron"},                                   GORON_MASK,                   (u32)GetItemID::GI_MASK_GORON,              ITEMTYPE_MASK);
    itemTable[ZORA_MASK]                     = Item(true,  false, &ZoraMask,                Text{"Zora Mask",                    "Masque Zora",                                     "Máscara Zora"},                                    ZORA_MASK,                    (u32)GetItemID::GI_MASK_ZORA,               ITEMTYPE_MASK);
    itemTable[DEKU_MASK]                     = Item(true,  false, &DekuMask,                Text{"Deku Mask",                    "Masque Mojo",                                     "Máscara Deku"},                                    DEKU_MASK,                    (u32)GetItemID::GI_MASK_DEKU,               ITEMTYPE_MASK);
    itemTable[POSTMANS_HAT]                  = Item(true,  false, &PostmansHat,             Text{"Postman's Hat",                "Casquette de facteur",                            "Gorra de cartero"},                                POSTMANS_HAT,                 (u32)GetItemID::GI_MASK_POSTMANS,           ITEMTYPE_MASK);
    itemTable[ALL_NIGHT_MASK]                = Item(true,  false, &AllNightMask,            Text{"All-Night Mask",               "Masque de la nuit blanche",                       "Máscara para trasnochar"},                         ALL_NIGHT_MASK,               (u32)GetItemID::GI_MASK_ALL_NIGHT,          ITEMTYPE_MASK);
    itemTable[BLAST_MASK]                    = Item(true,  false, &BlastMask,               Text{"Blast Mask",                   "Masque d'explosion",                              "Máscara explosiva"},                               BLAST_MASK,                   (u32)GetItemID::GI_MASK_BLAST,              ITEMTYPE_MASK);
    itemTable[STONE_MASK]                    = Item(true,  false, &StoneMask,               Text{"Stone Mask",                   "Masque de la pierre",                             "Máscara de piedra"},                               STONE_MASK,                   (u32)GetItemID::GI_MASK_STONE,              ITEMTYPE_MASK);
    itemTable[GREAT_FAIRYS_MASK]             = Item(true,  false, &GreatFairyMask,          Text{"Great Fairy's Mask",           "Masque des grandes fées",                         "Máscara de gran hada"},                            GREAT_FAIRYS_MASK,            (u32)GetItemID::GI_MASK_GREAT_FAIRYS,       ITEMTYPE_MASK);
    itemTable[BREMEN_MASK]                   = Item(true,  false, &BremenMask,              Text{"Bremen Mask",                  "Masque de Brême",                                 "Máscara de Bremen"},                               BREMEN_MASK,                  (u32)GetItemID::GI_MASK_BREMEN,             ITEMTYPE_MASK);
    itemTable[DON_GEROS_MASK]                = Item(true,  false, &DonGerosMask,            Text{"Don Gero's Mask",              "Masque de Don Gero",                              "Máscara de Don Gero"},                             DON_GEROS_MASK,               (u32)GetItemID::GI_MASK_DON_GEROS,          ITEMTYPE_MASK);
    itemTable[MASK_OF_SCENTS]                = Item(true,  false, &MaskOfScents,            Text{"Mask of Scents",               "Masque de parfums",                               "Máscara de aromas"},                               MASK_OF_SCENTS,               (u32)GetItemID::GI_MASK_OF_SCENTS,          ITEMTYPE_MASK);
    itemTable[ROMANIS_MASK]                  = Item(true,  false, &RomanisMask,             Text{"Romani's Mask",                "Masque Romani",                                   "Máscara de Romani"},                               ROMANIS_MASK,                 (u32)GetItemID::GI_MASK_ROMANIS,            ITEMTYPE_MASK);
    itemTable[CIRCUS_LEADERS_MASK]           = Item(true,  false, &CircusLeadersMask,       Text{"Troupe Leader's Mask",         "Masque de chef de la troupe",                     "Máscara del jefe de la compañía"},                 CIRCUS_LEADERS_MASK,          (u32)GetItemID::GI_MASK_TROUPE_LEADERS,     ITEMTYPE_MASK);
    itemTable[KAFEIS_MASK]                   = Item(true,  false, &KafeisMask,              Text{"Kafei's Mask",                 "Masque de Kafei",                                 "Máscara de Kafei"},                                KAFEIS_MASK,                  (u32)GetItemID::GI_MASK_KAFEIS,             ITEMTYPE_MASK);
    itemTable[COUPLES_MASK]                  = Item(true,  false, &CouplesMask,             Text{"Couple's Mask",                "Masque des amoureux",                             "Máscara de los novios"},                           COUPLES_MASK,                 (u32)GetItemID::GI_MASK_COUPLES,            ITEMTYPE_MASK);
    itemTable[KAMAROS_MASK]                  = Item(true,  false, &KamarosMask,             Text{"Kamaro's Mask",                "Masque de Kamaro",                                "Máscara de Kamaro"},                               KAMAROS_MASK,                 (u32)GetItemID::GI_MASK_KAMARAOS,           ITEMTYPE_MASK);
    itemTable[GIBDOS_MASK]                   = Item(true,  false, &GibdosMask,              Text{"Gibdo Mask",                   "Masque de gibdo",                                 "Máscara de Gibdo"},                                GIBDOS_MASK,                  (u32)GetItemID::GI_MASK_GIBDO,              ITEMTYPE_MASK);
    itemTable[GAROS_MASK]                    = Item(true,  false, &GarosMask,               Text{"Garo's Mask",                  "Cagoule Garo",                                    "Máscara de Garo"},                                 GAROS_MASK,                   (u32)GetItemID::GI_MASK_GARO,               ITEMTYPE_MASK);
    itemTable[CAPTAINS_HAT]                  = Item(true,  false, &CaptainsHat,             Text{"Captain's Hat",                "Heaume du capitaine",                             "Casco del capitán"},                               CAPTAINS_HAT,                 (u32)GetItemID::GI_MASK_CAPTAINS_HAT,       ITEMTYPE_MASK);
    itemTable[GIANTS_MASK]                   = Item(true,  false, &GiantsMask,              Text{"Giant's Mask",                 "Masque du géant",                                 "Máscara del gigante"},                             GIANTS_MASK,                  (u32)GetItemID::GI_MASK_GIANTS,             ITEMTYPE_MASK);
    itemTable[FIERCE_DEITY_MASK]             = Item(true,  false, &FierceDeityMask,         Text{"Fierce Deity Mask",            "Masque du Dieu Démon",                            "Máscara de la Fiera Deidad"},                      FIERCE_DEITY_MASK,            (u32)GetItemID::GI_MASK_FIERCE_DEITY,       ITEMTYPE_MASK);
    itemTable[MASK_OF_TRUTH]                 = Item(true,  false, &MaskOfTruth,             Text{"Mask of Truth",                "Masque de vérité",                                "Máscara de la verdad"},                            MASK_OF_TRUTH,                (u32)GetItemID::GI_MASK_OF_TRUTH,           ITEMTYPE_MASK);
    itemTable[FISHING_PASS]                  = Item(false, false, &noVariable,              Text{"Fishing Pass",                 "Ticket de pêche",                                 "Entrada de la zona de pesca"},                     FISHING_PASS,                 0xBA,                                       ITEMTYPE_ITEM);

//Swamp Spider Tokens
    itemTable[SWAMP_SKULLTULA_TOKEN]         = Item(true,  false, &SwampSkulltulaTokens,    Text{"Swamp Skulltula Token",        "Âme de skulltula d'or du marais",                 "Espíritu de skulltula dorada"},                    SWAMP_SKULLTULA_TOKEN,        0x44,                                       ITEMTYPE_TOKEN);

//Oceanside Spider Tokens
    itemTable[OCEANSIDE_SKULLTULA_TOKEN]     = Item(true,  false, &OceanSkulltulaTokens,    Text{"Oceanside Skulltula Token",    "Âme de skulltula d'or de la côte",                "Espíritu de skulltula dorada"},                    OCEANSIDE_SKULLTULA_TOKEN,    0x6D,                                       ITEMTYPE_TOKEN);

//Stray Fairies//

//Clock Town Fairies
    itemTable[CT_STRAY_FAIRY]                = Item(true,  false, &ClockTownStrayFairy,     Text{"Clock Town Stray Fairy",       "Fée égarée de Bourg-Clocher",                     "Hada Extraviada de la Ciudad"},                    CT_STRAY_FAIRY,               (u32)GetItemID::GI_NONE,                    ITEMTYPE_STRAYFAIRY);

//Woodfall Stray Fairies
    itemTable[WF_STRAY_FAIRY]                = Item(true,  false, &WoodfallStrayFairies,    Text{"Woodfall Stray Fairy",         "Fée égarée du Bois-Cascade",                      "Hada Extraviada del Bosque Catarata"},             WF_STRAY_FAIRY,               (u32)GetItemID::GI_NONE,                    ITEMTYPE_STRAYFAIRY);

//Snowhead Stray Fairies
    itemTable[SH_STRAY_FAIRY]                = Item(true,  false, &SnowheadStrayFairies,    Text{"Snowhead Stray Fairy",         "Fée égarée du pic des Neiges",                    "Hada Extraviada del Pico Nevado"},                 SH_STRAY_FAIRY,               (u32)GetItemID::GI_NONE,                    ITEMTYPE_STRAYFAIRY);

//Great Bay Stray Fairies
    itemTable[GBT_STRAY_FAIRY]               = Item(true,  false, &GreatBayStrayFairies,    Text{"Great Bay Stray Fairy",        "Fée égarée de la Grande Baie",                    "Hada Extraviada de la Gran Bahía"},                GBT_STRAY_FAIRY,              (u32)GetItemID::GI_NONE,                    ITEMTYPE_STRAYFAIRY);

//Stone Tower Stray Fairies
    itemTable[ST_STRAY_FAIRY]                = Item(true,  false, &StoneTowerStrayFairies,  Text{"Stone Tower Stray Fairy",      "Fée égarée de la Forteresse de Pierre",           "Hada Extraviada de la Torre de Piedra"},           ST_STRAY_FAIRY,               (u32)GetItemID::GI_NONE,                    ITEMTYPE_STRAYFAIRY);

//Bottles
    itemTable[EMPTY_BOTTLE1]                 = Item(true,  false, &ArcheryBottle,           Text{"Empty Bottle",                 "Flacon vide",                                     "Botella vacía"},                                   EMPTY_BOTTLE1,                (u32)GetItemID::GI_BOTTLE_EMPTY,            ITEMTYPE_ITEM);
    itemTable[EMPTY_BOTTLE2]                 = Item(true,  false, &BeaverRaceBottle,        Text{"Empty Bottle",                 "Flacon vide",                                     "Botella vacía"},                                   EMPTY_BOTTLE2,                (u32)GetItemID::GI_BOTTLE_EMPTY,            ITEMTYPE_ITEM);
    itemTable[EMPTY_BOTTLE]                  = Item(true,  false, &HasBottle,               Text{"Empty Bottle",                 "Flacon vide",                                     "Botella vacía"},                                   EMPTY_BOTTLE,                 (u32)GetItemID::GI_BOTTLE_EMPTY,            ITEMTYPE_ITEM);
    itemTable[BOTTLE_WITH_MILK]              = Item(true,  false, &AlienBottle,             Text{"Bottle with Milk",             "Flacon de lait",                                  "Botella de leche"},                                BOTTLE_WITH_MILK,             (u32)GetItemID::GI_BOTTLE_MILK,             ITEMTYPE_ITEM);
    itemTable[BOTTLE_WITH_RED_POTION]        = Item(true,  false, &WitchBottle,             Text{"Bottle with Red Potion",       "Flacon de potion rouge",                          "Botella de poción roja"},                          BOTTLE_WITH_RED_POTION,       (u32)GetItemID::GI_BOTTLE_POTION_RED,       ITEMTYPE_ITEM);
    itemTable[GOLD_DUST]                     = Item(true,  true,  &GoronRaceBottle,         Text{"Gold Dust",                    "Poudre d'Or",                                     "Polvo de Oro"},                                    GOLD_DUST,                    (u32)GetItemID::GI_BOTTLE_GOLD_DUST,        ITEMTYPE_QUEST);
    itemTable[CHATEAU_ROMANI]                = Item(true,  false, &ChateauBottle,           Text{"Chateau Romani",               "Cuvée Romani",                                    "Reserva Romani"},                                  CHATEAU_ROMANI,               (u32)GetItemID::GI_BOTTLE_CHATEAU_ROMANI,   ITEMTYPE_ITEM);
    itemTable[BOTTLE_WITH_MYSTERY_MILK]      = Item(true,  true,  &MysteryMilkBottle,       Text{"Bottle with Mystery Milk",     "Flacon de lait suspect",                          "Botella de leche sospechosa"},                     BOTTLE_WITH_MYSTERY_MILK,     (u32)GetItemID::GI_BOTTLE_MYSTERY_MILK,     ITEMTYPE_QUEST);
//Other bottle items
    itemTable[DEKU_PRINCESS]                 = Item(true,  true,  &DekuPrincess,            Text{"Deku Princess",                "Princesse Mojo",                                  "Princesa Deku"},                                   DEKU_PRINCESS,                (u32)GetItemID::GI_DEKU_PRINCESS_FAIRY,     ITEMTYPE_ITEM);
    itemTable[BOTTLE_WITH_GREEN_POTION]      = Item(false, false, &HasBottle,               Text{"Bottle with Green Potion",     "Flacon de potion verte",                          "Botella de poción verde"},                         BOTTLE_WITH_GREEN_POTION,     (u32)GetItemID::GI_POTION_GREEN,            ITEMTYPE_ITEM);
    itemTable[BOTTLE_WITH_BLUE_POTION]       = Item(false, false, &HasBottle,               Text{"Bottle with Blue Potion",      "Flacon de potion bleue",                          "Botella de poción azul"},                          BOTTLE_WITH_BLUE_POTION,      (u32)GetItemID::GI_POTION_BLUE,             ITEMTYPE_ITEM);
    itemTable[BOTTLE_WITH_FAIRY]             = Item(false, false, &HasBottle,               Text{"Bottle with Fairy",            "Fée en flacon",                                   "Botella con hada"},                                BOTTLE_WITH_FAIRY,            (u32)GetItemID::GI_FAIRY,                   ITEMTYPE_ITEM);
    itemTable[BOTTLE_WITH_BUGS]              = Item(false, false, &HasBottle,               Text{"Bottle with Bugs",             "Insecte en flacon",                               "Botella con insecto"},                             BOTTLE_WITH_BUGS,             (u32)GetItemID::GI_BOTTLE_BUG,              ITEMTYPE_ITEM);
    itemTable[BOTTLE_WITH_FISH]              = Item(false, false, &HasBottle,               Text{"Bottle with Fish",             "Poisson en flacon",                               "Botella con pez"},                                 BOTTLE_WITH_FISH,             (u32)GetItemID::GI_BOTTLE_FISH,             ITEMTYPE_ITEM);
    itemTable[BOTTLE_WITH_POE]               = Item(false, false, &HasBottle,               Text{"Bottle with Poe",              "Esprit en flacon",                                "Botella con Poe"},                                 BOTTLE_WITH_POE,              (u32)GetItemID::GI_BOTTLE_POE_TEXT,         ITEMTYPE_ITEM);
    itemTable[BOTTLE_WITH_BIG_POE]           = Item(false, false, &HasBottle,               Text{"Bottle with Big Poe",          "Âme en flacon",                                   "Botella con Gran Poe"},                            BOTTLE_WITH_BIG_POE,          (u32)GetItemID::GI_BOTTLE_BIG_POE,          ITEMTYPE_ITEM);
    itemTable[BOTTLE_WITH_SPRING_WATER]      = Item(false, false, &HasBottle,               Text{"Bottle with Spring Water",     "Flacon d'eau de source",                          "Botella con agua de manantial"},                   BOTTLE_WITH_SPRING_WATER,     (u32)GetItemID::GI_BOTTLE_SPRING_WATER,     ITEMTYPE_ITEM);
    itemTable[BOTTLE_WITH_HOT_SPRING_WATER]  = Item(false, false, &HasBottle,               Text{"Bottle with Hot Spring Water", "Flacon d'eau de source chaude",                   "Botella con agua caliente de manantial"},          BOTTLE_WITH_HOT_SPRING_WATER, (u32)GetItemID::GI_BOTTLE_HOT_SPRING_WATER, ITEMTYPE_ITEM);
    itemTable[BOTTLE_WITH_ZORA_EGG]          = Item(false, true,  &HasBottle,               Text{"Bottle with Zora Egg",         "Œuf de Zora en flacon",                           "Botella con huevo Zora"},                          BOTTLE_WITH_ZORA_EGG,         (u32)GetItemID::GI_BOTTLE_ZORA_EGG,         ITEMTYPE_ITEM);
    itemTable[BOTTLE_WITH_MUSHROOM]          = Item(false, false, &HasBottle,               Text{"Bottle with Mushroom",         "Champignon magique en flacon",                    "Botella con champiñón mágico"},                    BOTTLE_WITH_MUSHROOM,         (u32)GetItemID::GI_BOTTLE_MAGIC_MUSHROOM,   ITEMTYPE_ITEM);
    itemTable[ZORA_EGG]                      = Item(false, true,  &ZoraEgg,                 Text{"Zora Egg",                     "Œuf de Zora",                                     "Huevo Zora"},                                      ZORA_EGG,                     (u32)GetItemID::GI_BOTTLE_ZORA_EGG,         ITEMTYPE_ITEM);
    itemTable[SEAHORSE]                      = Item(true,  true,  &Seahorse,                Text{"Seahorse",                     "Hippocampe",                                      "Caballo de mar"},                                  SEAHORSE,                     (u32)GetItemID::GI_BOTTLE_SEAHORSE,         ITEMTYPE_ITEM);

//Upgrades
    itemTable[RAZOR_SWORD]                   = Item(true,  false, &RazorSword,              Text{"Razor Sword",                  "Lame Rasoir",                                     "Espada Afilada"},                                  RAZOR_SWORD,                  (u32)GetItemID::GI_RAZOR_SWORD,             ITEMTYPE_ITEM);
    itemTable[GILDED_SWORD]                  = Item(true,  false, &GildedSword,             Text{"Gilded Sword",                 "Lame Dorée",                                      "Espada de Esmeril"},                               GILDED_SWORD,                 (u32)GetItemID::GI_GILDED_SWORD,            ITEMTYPE_ITEM);
    itemTable[MIRROR_SHIELD]                 = Item(true,  false, &MirrorShield,            Text{"Mirror Shield",                "Bouclier miroir",                                 "Escudo espejo"},                                   MIRROR_SHIELD,                (u32)GetItemID::GI_SHIELD_MIRROR,           ITEMTYPE_ITEM);
    itemTable[LARGE_QUIVER]                  = Item(true,  false, &TownArcheryQuiver,       Text{"Large Quiver",                 "Grand carquois",                                  "Carcaj grande"},                                   LARGE_QUIVER,                 (u32)GetItemID::GI_LARGE_QUIVER,            ITEMTYPE_ITEM);
    itemTable[LARGEST_QUIVER]                = Item(true,  false, &SwampArcheryQuiver,      Text{"Largest Quiver",               "Énorme carquois",                                 "Carcaj gigante"},                                  LARGEST_QUIVER,               (u32)GetItemID::GI_LARGEST_QUIVER,          ITEMTYPE_ITEM);
    itemTable[BOMB_BAG]                      = Item(true,  false, &BombBag20,               Text{"Bomb Bag",                     "Sac de bombes",                                   "Saco de bombas"},                                  BOMB_BAG,                     (u32)GetItemID::GI_BOMB_BAG_20,             ITEMTYPE_ITEM);
    itemTable[BIG_BOMB_BAG]                  = Item(true,  false, &TownBombBag,             Text{"Big Bomb Bag",                 "Grand sac de bombes",                             "Saco de bombas grande"},                           BIG_BOMB_BAG,                 (u32)GetItemID::GI_BOMB_BAG_30,             ITEMTYPE_ITEM);
    itemTable[BIGGEST_BOMB_BAG]              = Item(true,  false, &MountainBombBag,         Text{"Biggest Bomb Bag",             "Énorme sac de bombes",                            "Saco de bombas gigante"},                          BIGGEST_BOMB_BAG,             (u32)GetItemID::GI_BOMB_BAG_40,             ITEMTYPE_ITEM);
    itemTable[ADULT_WALLET]                  = Item(true,  false, &Townwallet200,           Text{"Adult Wallet",                 "Grande bourse",                                   "Bolsa de rupias grande"},                          ADULT_WALLET,                 (u32)GetItemID::GI_ADULT_WALLET,            ITEMTYPE_ITEM);
    itemTable[GIANT_WALLET]                  = Item(true,  false, &OceanWallet500,          Text{"Giant Wallet",                 "Bourse de géant",                                 "Bolsa de rupias gigante"},                         GIANT_WALLET,                 (u32)GetItemID::GI_GIANT_WALLET,            ITEMTYPE_ITEM);
    itemTable[MAGIC_POWER]                   = Item(true,  false, &MagicPower,              Text{"Magic Power",                  "Énergie magique",                                 "Poder mágico"},                                    MAGIC_POWER,                  (u32)GetItemID::GI_NONE,                    ITEMTYPE_ITEM);
    itemTable[EXTENDED_MAGIC_POWER]          = Item(true,  false, &ExtendedMagicPower,      Text{"Extended Magic Power",         "Énergie magique doublée",                         "Poder mágico extendido"},                          EXTENDED_MAGIC_POWER,         (u32)GetItemID::GI_NONE,                    ITEMTYPE_ITEM);

//Songs
    itemTable[SONG_OF_TIME]                  = Item(true,  false, &SongOfTime,              Text{"Song of Time",                 "Chant du temps",                                  "Canción del tiempo"},                              SONG_OF_TIME,                 (u32)0x53,                                  ITEMTYPE_SONG);
    itemTable[SONG_OF_STORMS]                = Item(true,  false, &SongOfStorms,            Text{"Song of Storms",               "Chant des tempêtes",                              "Canción de la tormenta"},                          SONG_OF_STORMS,               (u32)0x73,                                  ITEMTYPE_SONG);
    itemTable[SONATA_OF_AWAKENING]           = Item(true,  false, &SonataOfAwakening,       Text{"Sonata of Awakening",          "Sonate de l'éveil",                               "Sonata del despertar"},                            SONATA_OF_AWAKENING,          (u32)0x4B,                                  ITEMTYPE_SONG);
    itemTable[LULLABY_INTRO]                 = Item(true,  false, &LullabyIntro,            Text{"Goron's Lullaby Intro",        "Intro de la Berceuse",                            "Introducción de la nana"},                         LULLABY_INTRO,                (u32)0x74,                                  ITEMTYPE_SONG);
    itemTable[GORONS_LULLABY]                = Item(true,  false, &GoronsLullaby,           Text{"Goron's Lullaby",              "Berceuse des Gorons",                             "Nana goron"},                                      GORONS_LULLABY,               (u32)0x4D,                                  ITEMTYPE_SONG);
    itemTable[NEW_WAVE_BOSSA_NOVA]           = Item(true,  false, &NewWaveBossaNova,        Text{"New Wave Bossa Nova",          "Bossa-nova de flots",                             "Bossanova de las olas"},                           NEW_WAVE_BOSSA_NOVA,          (u32)0x4E,                                  ITEMTYPE_SONG);
    itemTable[ELEGY_OF_EMPTINESS]            = Item(true,  false, &ElegyOfEmptiness,        Text{"Elegy of Emptiness",           "Hymne du vide",                                   "Elegía al vacío"},                                 ELEGY_OF_EMPTINESS,           (u32)0x4F,                                  ITEMTYPE_SONG);
    itemTable[OATH_TO_ORDER]                 = Item(true,  false, &OathToOrder,             Text{"Oath to Order",                "Ode de l'appel",                                  "Oda al orden"},                                    OATH_TO_ORDER,                (u32)0x51,                                  ITEMTYPE_SONG);
    itemTable[EPONAS_SONG]                   = Item(true,  false, &EponasSong,              Text{"Epona's Song",                 "Chant d'Épona",                                   "Canción de Epona"},                                EPONAS_SONG,                  (u32)0x6C,                                  ITEMTYPE_SONG);
  //itemTable[INVERTED_SONG_OF_TIME]         = Item(true,  false, &InvertedSongOfTime,      Text{"Inverted Song of Time",        "Chant du Temps Inversé",                          "Canción del tiempo invertida"},                    INVERTED_SONG_OF_TIME,        0xC2,                                       ITEMTYPE_SONG);
  //itemTable[SONG_OF_DOUBLE_TIME]           = Item(true,  false, &SongOfDoubleTime,        Text{"Song of Double Time",          "Chant du Temps Accéléré",                         "Canción del doble tiempo"},                        SONG_OF_DOUBLE_TIME,          0xC3,                                       ITEMTYPE_SONG);
    itemTable[SONG_OF_HEALING]               = Item(true,  false, &SongOfHealing,           Text{"Song of Healing",              "Chant de l'Apaisement",                           "Canción de curación"},                             SONG_OF_HEALING,              (u32)0x54,                                  ITEMTYPE_SONG);
    itemTable[SONG_OF_SOARING]               = Item(true,  false, &SongOfSoaring,           Text{"Song of Soaring",              "Chant de l'Envol",                                "Canción de vuelo"},                                SONG_OF_SOARING,              (u32)0x72,                                  ITEMTYPE_SONG);

//Maps and Compasses
    itemTable[WOODFALL_TEMPLE_MAP]           = Item(false, false, &noVariable,              Text{"Woodfall Temple Map",          "Carte du Temple de Bois-Cascade",                 "Mapa del Templo del Bosque Catarata"},             WOODFALL_TEMPLE_MAP,          (u32)0xAE,                                  ITEMTYPE_MAP);
    itemTable[SNOWHEAD_TEMPLE_MAP]           = Item(false, false, &noVariable,              Text{"Snowhead Temple Map",          "Carte du Temple du Pic des Neiges",               "Mapa del Templo del Pico Nevado"},                 SNOWHEAD_TEMPLE_MAP,          (u32)0xAF,                                  ITEMTYPE_MAP);
    itemTable[GBT_MAP]                       = Item(false, false, &noVariable,              Text{"Great Bay Temple Map",         "Carte du Temple de la Grande Baie",               "Mapa del Templo de la Gran Bahía"},                GBT_MAP,                      (u32)0xB0,                                  ITEMTYPE_MAP);
    itemTable[STONE_TOWER_TEMPLE_MAP]        = Item(false, false, &noVariable,              Text{"Stone Tower Temple Map",       "Carte du Temple de la Forteresse de Pierre",      "Mapa del Templo de la Torre de Piedra"},           STONE_TOWER_TEMPLE_MAP,       (u32)0xB1,                                  ITEMTYPE_MAP);
    itemTable[CLOCK_TOWN_MAP]                = Item(false, false, &noVariable,              Text{"Clock Town Map",               "Carte de Bourg-Clocher",                          "Mapa de la Ciudad Reloj"},                         CLOCK_TOWN_MAP,               (u32)GetItemID::GI_MAP_OF_CLOCK_TOWN,       ITEMTYPE_MAP);
    itemTable[WOODFALL_MAP]                  = Item(false, false, &noVariable,              Text{"Woodfall Map",                 "Carte de Bois-Cascade",                           "Mapa del Bosque Catarata"},                        WOODFALL_MAP,                 (u32)GetItemID::GI_MAP_OF_WOODFALL,         ITEMTYPE_MAP);
    itemTable[SNOWHEAD_MAP]                  = Item(false, false, &noVariable,              Text{"Snowhead Map",                 "Carte du pic Des Neiges",                         "Mapa del Pico Nevado"},                            SNOWHEAD_MAP,                 (u32)GetItemID::GI_MAP_OF_SNOWHEAD,         ITEMTYPE_MAP);
    itemTable[GREAT_BAY_MAP]                 = Item(false, false, &noVariable,              Text{"Great Bay Map",                "Carte de la Grande Baie",                         "Mapa de la Gran Bahía"},                           GREAT_BAY_MAP,                (u32)GetItemID::GI_MAP_OF_GREAT_BAY,        ITEMTYPE_MAP);
    itemTable[STONE_TOWER_MAP]               = Item(false, false, &noVariable,              Text{"Stone Tower Map",              "Carte de la Forteresse de Pierre",                "Mapa de la Torre de Piedra"},                      STONE_TOWER_MAP,              (u32)GetItemID::GI_MAP_OF_STONE_TOWER,      ITEMTYPE_MAP);
    itemTable[ROMANI_RANCH_MAP]              = Item(false, false, &noVariable,              Text{"Romani Ranch Map",             "Carte du ranch Romani",                           "Mapa del Rancho Romani"},                          ROMANI_RANCH_MAP,             (u32)GetItemID::GI_MAP_OF_ROMANI_RANCH,     ITEMTYPE_MAP);

    itemTable[WOODFALL_TEMPLE_COMPASS]       = Item(false, false, &noVariable,              Text{"Woodfall Temple Compass",      "Boussole de Temple de Bois-Cascade",              "Brújula del Templo del Bosque Catarata"},          WOODFALL_TEMPLE_COMPASS,      (u32)0xA7,                                  ITEMTYPE_COMPASS);
    itemTable[SNOWHEAD_TEMPLE_COMPASS]       = Item(false, false, &noVariable,              Text{"Snowhead Temple Compass",      "Boussole de Temple du Pic des Neiges",            "Brújula del Templo del Pico Nevado"},              SNOWHEAD_TEMPLE_COMPASS,      (u32)0xA8,                                  ITEMTYPE_COMPASS);
    itemTable[GBT_COMPASS]                   = Item(false, false, &noVariable,              Text{"Great Bay Temple Compass",     "Boussole de Temple de la Grande Baie",            "Brújula del Templo de la Gran Bahía"},             GBT_COMPASS,                  (u32)0xAC,                                  ITEMTYPE_COMPASS);
    itemTable[STONE_TOWER_TEMPLE_COMPASS]    = Item(false, false, &noVariable,              Text{"Stone Tower Temple Compass",   "Boussole du Temple de la Forteresse de Pierre",   "Brújula del Templo de la Torre de Piedra"},        STONE_TOWER_TEMPLE_COMPASS,   (u32)0xAD,                                  ITEMTYPE_COMPASS);

//Boss Keys
    itemTable[WOODFALL_TEMPLE_BOSS_KEY]      = Item(true,  false, &BossKeyWoodfallTemple,   Text{"Woodfall Temple Big Key",      "Grande clé du Temple de Bois-Cascade",            "Gran llave del Templo del Bosque Catarata"},       WOODFALL_TEMPLE_BOSS_KEY,     (u32)0xA3,                                  ITEMTYPE_BOSSKEY);
    itemTable[SNOWHEAD_TEMPLE_BOSS_KEY]      = Item(true,  false, &BossKeySnowheadTemple,   Text{"Snowhead Temple Big Key",      "Grande clé du Temple du Pic des Neiges",          "Gran llave del Templo del Pico Nevado"},           SNOWHEAD_TEMPLE_BOSS_KEY,     (u32)0xA4,                                  ITEMTYPE_BOSSKEY);
    itemTable[GBT_BOSS_KEY]                  = Item(true,  false, &BossKeyGreatBayTemple,   Text{"Great Bay Temple Big Key",     "Grande clé du Temple de la Grande Baie",          "Gran llave del Templo de la Gran Bahía"},          GBT_BOSS_KEY,                 (u32)0xA5,                                  ITEMTYPE_BOSSKEY);
    itemTable[STONE_TOWER_TEMPLE_BOSS_KEY]   = Item(true,  false, &BossKeyStoneTowerTemple, Text{"Stone Tower Temple Big Key",   "Grande clé du Temple de la Forteresse de Pierre", "Gran llave del Templo de la Torre de Piedra"},     STONE_TOWER_TEMPLE_BOSS_KEY,  (u32)0xA6,                                  ITEMTYPE_BOSSKEY);
//Small Keys
    itemTable[WOODFALL_TEMPLE_SMALL_KEY]     = Item(true,  false, &WoodfallTempleKeys,      Text{"Woodfall Temple Small Key",    "Petite clé du Temple de Bois-Cascade",            "Llave del Templo del Templo del Bosque Catarata"}, WOODFALL_TEMPLE_SMALL_KEY,    (u32)0x76,                                  ITEMTYPE_SMALLKEY);
    itemTable[SNOWHEAD_TEMPLE_SMALL_KEY]     = Item(true,  false, &SnowheadTempleKeys,      Text{"Snowhead Temple Small Key",    "Petite clé du Temple du Pic des Neiges",          "Llave del Templo del Pico Nevado"},                SNOWHEAD_TEMPLE_SMALL_KEY,    (u32)0x77,                                  ITEMTYPE_SMALLKEY);
    itemTable[GBT_SMALL_KEY]                 = Item(true,  false, &GreatBayTempleKeys,      Text{"Great Bay Temple Small Key",   "Petite clé du Temple de la Grande Baie",          "Llave del Templo del la Gran Bahia"},              GBT_SMALL_KEY,                (u32)0x90,                                  ITEMTYPE_SMALLKEY);
    itemTable[STONE_TOWER_TEMPLE_SMALL_KEY]  = Item(true,  false, &StoneTowerTempleKeys,    Text{"Stone Tower Temple Small Key", "Petite clé du Temple de la Forteresse de Pierre", "Llave del Templo de la Torre de Piedra"},          STONE_TOWER_TEMPLE_SMALL_KEY, (u32)0xA2,                                  ITEMTYPE_SMALLKEY);

//Boss Remains
    itemTable[ODOLWAS_REMAINS]               = Item(true,  false, &OdolwaRemains,           Text{"Odolwa's Remains",             "Restes d'Odolwa",                                 "Restos de Odolwa"},                                ODOLWAS_REMAINS,              (u32)GetItemID::GI_ODOLWAS_REMAINS,         ITEMTYPE_DUNGEONREWARD);
    itemTable[GOHTS_REMAINS]                 = Item(true,  false, &GohtRemains,             Text{"Goht's Remains",               "Restes de Rhork",                                 "Restos de Goht"},                                  GOHTS_REMAINS,                (u32)GetItemID::GI_GOHTS_REMAINS,           ITEMTYPE_DUNGEONREWARD);
    itemTable[GYORGS_REMAINS]                = Item(true,  false, &GyorgRemains,            Text{"Gyorg's Remains",              "Restes de Gyorg",                                 "Restos de Gyorg"},                                 GYORGS_REMAINS,               (u32)GetItemID::GI_GYORGS_REMAINS,          ITEMTYPE_DUNGEONREWARD);
    itemTable[TWINMOLDS_REMAINS]             = Item(true,  false, &TwinmoldRemains,         Text{"Twinmold's Remains",           "Restes de Skorn",                                 "Restos de Twinmold"},                              TWINMOLDS_REMAINS,            (u32)GetItemID::GI_TWINMOLDS_REMAINS,       ITEMTYPE_DUNGEONREWARD);

//Pre Clock Town??
    //itemTable[PRE_CLOCK_TOWN_CHEST] = Item(false,0, &noVariable, Text{ "Deku Nuts (10)", "Noix Mojo (10)", "Nueces deku (10)" }, "Pre-Clock Town Chest", Region::BeneathClockTown, PRE_CLOCK_TOWN_CHEST, (u32)GetItemID::GI_NUTS_10, ItemCategory::DekuNuts, LocationCategory::GlitchesRequired);

//Generic Items
    itemTable[RECOVERY_HEART]                = Item(false, false, &noVariable,              Text{"Recovery Heart",               "Cœur de vie",                                     "Corazón"},                                         RECOVERY_HEART,               (u32)GetItemID::GI_RECOVERY_HEART_SINGLE,   ITEMTYPE_ITEM);
    itemTable[GREEN_RUPEE]                   = Item(false, false, &noVariable,              Text{"Green Rupee",                  "Rubis vert",                                      "Rupia verde"},                                     GREEN_RUPEE,                  (u32)GetItemID::GI_RUPEE_GREEN,             ITEMTYPE_ITEM);
    itemTable[BLUE_RUPEE]                    = Item(false, false, &noVariable,              Text{"Blue Rupee",                   "Rubis bleu",                                      "Rupia azul"},                                      BLUE_RUPEE,                   (u32)GetItemID::GI_RUPEE_BLUE,              ITEMTYPE_ITEM);
    itemTable[RED_RUPEE]                     = Item(false, false, &noVariable,              Text{"Red Rupee",                    "Rubis rouge",                                     "Rupia roja"},                                      RED_RUPEE,                    (u32)GetItemID::GI_RUPEE_RED,               ITEMTYPE_ITEM);
    itemTable[PURPLE_RUPEE]                  = Item(false, false, &noVariable,              Text{"Purple Rupee",                 "Rubis violet",                                    "Rupia morada"},                                    PURPLE_RUPEE,                 (u32)GetItemID::GI_RUPEE_PURPLE,            ITEMTYPE_ITEM);
    itemTable[HUGE_RUPEE]                    = Item(false, false, &noVariable,              Text{"Huge Rupee",                   "Énorme rubis",                                    "Rupia gigante"},                                   HUGE_RUPEE,                   (u32)GetItemID::GI_RUPEE_GOLD,              ITEMTYPE_ITEM);
    itemTable[SILVER_RUPEE]                  = Item(false, false, &noVariable,              Text{"Silver Rupee",                 "Rubis argenté",                                   "Rupia de plata"},                                  SILVER_RUPEE,                 (u32)GetItemID::GI_RUPEE_SILVER,            ITEMTYPE_ITEM);
    itemTable[PIECE_OF_HEART]                = Item(true,  false, &PiecesOfHeart,           Text{"Piece of Heart",               "Fragment de cœur",                                "Pieza de corazón"},                                PIECE_OF_HEART,               (u32)GetItemID::GI_HEART_PIECE,             ITEMTYPE_ITEM);
    itemTable[HEART_CONTAINER]               = Item(true,  false, &HeartContainers,         Text{"Heart Container",              "Réceptacle de cœur",                              "Contenedor de corazón"},                           HEART_CONTAINER,              (u32)GetItemID::GI_HEART_CONTAINER,         ITEMTYPE_ITEM);
    itemTable[ICE_TRAP]                      = Item(false, false, &noVariable,              Text{"Ice Trap",                     "Piège de glace",                                  "Trampa de hielo"},                                 ICE_TRAP,                     0x12,                                       ITEMTYPE_ITEM);
    itemTable[MILK]                          = Item(false, false, &HasBottle,               Text{"Milk",                         "Lait",                                            "Leche"},                                           NONE,                         0x92,                                       ITEMTYPE_ITEM);

//Refills
    itemTable[BOMBS_5]                       = Item(false, false, &noVariable,              Text{"Bombs (5)",                    "Bombes (5)",                                      "Bombas (5)"},                                      BOMBS_5,                      (u32)GetItemID::GI_BOMBS_5,                 ITEMTYPE_REFILL);
    itemTable[BOMBS_10]                      = Item(false, false, &noVariable,              Text{"Bombs (10)",                   "Bombes (10)",                                     "Bombas (10)"},                                     BOMBS_10,                     (u32)GetItemID::GI_BOMBS_10,                ITEMTYPE_REFILL);
    itemTable[BOMBS_20]                      = Item(false, false, &noVariable,              Text{"Bombs (20)",                   "Bombes (20)",                                     "Bombas (20)"},                                     BOMBS_20,                     (u32)GetItemID::GI_BOMBS_20,                ITEMTYPE_REFILL);
    itemTable[BOMBCHU_5]                     = Item(false, false, &noVariable,              Text{"Bombchu (5)",                  "Missiles Teigneux (5)",                           "Bombchus (5)"},                                    BOMBCHU_5,                    (u32)GetItemID::GI_BOMBCHUS_5,              ITEMTYPE_REFILL);
    itemTable[BOMBCHU_10]                    = Item(false, false, &noVariable,              Text{"Bombchu (10)",                 "Missiles Teigneux (10)",                          "Bombchus (10)"},                                   BOMBCHU_10,                   (u32)GetItemID::GI_BOMBCHUS_10,             ITEMTYPE_REFILL);
    itemTable[BOMBCHU_20]                    = Item(false, false, &noVariable,              Text{"Bombchu (20)",                 "Missiles Teigneux (20)",                          "Bombchus (20)"},                                   BOMBCHU_20,                   (u32)GetItemID::GI_BOMBCHU_20,              ITEMTYPE_REFILL);
  //itemTable[BOMBCHU_DROP]                  = Item(false, true,  &BombchuDrop,             Text{"Bombchu Drop",                 "Missiles Teigneux",                               "Bombchus"},                                        NONE,                         (u32)GetItemID::GI_BOMBCHUS_10,             ITEMTYPE_DROP);
    itemTable[ARROWS_10]                     = Item(false, false, &noVariable,              Text{"Arrows (10)",                  "Flèches (10)",                                    "Flechas (10)"},                                    ARROWS_10,                    0x1E,                                       ITEMTYPE_REFILL);
    itemTable[ARROWS_30]                     = Item(false, false, &noVariable,              Text{"Arrows (30)",                  "Flèches (30)",                                    "Flechas (30)"},                                    ARROWS_30,                    0x1F,                                       ITEMTYPE_REFILL);
    itemTable[ARROWS_40]                     = Item(false, false, &noVariable,              Text{"Arrows (40)",                  "Flèches (40)",                                    "Flechas (40)"},                                    ARROWS_40,                    0x20,                                       ITEMTYPE_REFILL);
    itemTable[ARROWS_50]                     = Item(false, false, &noVariable,              Text{"Arrows (50)",                  "Flèches (50)",                                    "Flechas (50)"},                                    ARROWS_50,                    0x21,                                       ITEMTYPE_REFILL);
    itemTable[DEKU_NUTS_5]                   = Item(false, false, &noVariable,              Text{"Deku Nuts (5)",                "Noix Mojo (5)",                                   "Nueces deku (5)"},                                 DEKU_NUTS_5,                  (u32)GetItemID::GI_NUTS_5,                  ITEMTYPE_REFILL);
    itemTable[DEKU_NUTS_10]                  = Item(false, false, &noVariable,              Text{"Deku Nuts (10)",               "Noix Mojo (10)",                                  "Nueces deku (10)"},                                DEKU_NUTS_10,                 (u32)GetItemID::GI_NUTS_10,                 ITEMTYPE_REFILL);
    itemTable[DEKU_STICK_1]                  = Item(false, false, &noVariable,              Text{"Deku Stick (1)",               "Bâton Mojo (1)",                                  "Palo deku (1)"},                                   DEKU_STICK_1,                 (u32)GetItemID::GI_STICKS_1,                ITEMTYPE_REFILL);
    itemTable[RED_POTION_REFILL]             = Item(false, false, &noVariable,              Text{"Red Potion Refill",            "Potion rouge",                                    "Recarga de poción roja"},                          RED_POTION_REFILL,            (u32)GetItemID::GI_POTION_RED,              ITEMTYPE_REFILL);
    itemTable[GREEN_POTION_REFILL]           = Item(false, false, &noVariable,              Text{"Green Potion Refill",          "Potion verte",                                    "Recarga de poción verde"},                         GREEN_POTION_REFILL,          (u32)GetItemID::GI_POTION_GREEN,            ITEMTYPE_REFILL);
    itemTable[BLUE_POTION_REFILL]            = Item(false, false, &noVariable,              Text{"Blue Potion Refill",           "Potion bleue",                                    "Recarga de poción azul"},                          BLUE_POTION_REFILL,           (u32)GetItemID::GI_POTION_BLUE,             ITEMTYPE_REFILL);
    //Shop Items                                        repeatable, &price
    itemTable[BUY_ARROWS_10]                 = Item(false, false, &noVariable,              Text{"Buy Arrows (10)",              "Acheter: Flèches (10)",                           "Comprar flechas (10)"},                            BUY_ARROWS_10,                (u32)GetItemID::GI_ARROWS_MEDIUM,           ITEMTYPE_SHOP);
    itemTable[BUY_ARROWS_30]                 = Item(false, false, &noVariable,              Text{"Buy Arrows (30)",              "Acheter: Flèches (30)",                           "Comprar flechas (30)"},                            BUY_ARROWS_30,                (u32)GetItemID::GI_ARROWS_LARGE,            ITEMTYPE_SHOP);
    itemTable[BUY_DEKU_NUT_10]               = Item(false, false, &noVariable,              Text{"Buy Deku Nut (10)",            "Acheter: Noix Mojo (10)",                         "Comprar nueces deku (10)"},                        BUY_DEKU_NUT_10,              (u32)GetItemID::GI_NUTS_10,                 ITEMTYPE_SHOP);
    itemTable[BUY_DEKU_STICK_1]              = Item(false, false, &noVariable,              Text{"Buy Deku Stick (1)",           "Acheter: Bâton Mojo (1)",                         "Comprar palos deku (1)"},                          BUY_DEKU_STICK_1,             (u32)GetItemID::GI_STICKS_1,                ITEMTYPE_SHOP);
    itemTable[BUY_BOMBS_10]                  = Item(false, false, &noVariable,              Text{"Buy Bombs (10)",               "Acheter: Bombes (10)",                            "Comprar Bombas (10)"},                             BUY_BOMBS_10,                 (u32)GetItemID::GI_BOMBS_10,                ITEMTYPE_SHOP);
    itemTable[BUY_RED_POTION]                = Item(false, false, &noVariable,              Text{"Buy Red Potion ",              "Acheter: Potion rouge ",                          "Comprar poción roja "},                            BUY_RED_POTION,               (u32)GetItemID::GI_POTION_RED,              ITEMTYPE_SHOP);
    itemTable[BUY_GREEN_POTION]              = Item(false, false, &noVariable,              Text{"Buy Green Potion",             "Acheter: Potion verte",                           "Comprar poción verde"},                            BUY_GREEN_POTION,             (u32)GetItemID::GI_POTION_GREEN,            ITEMTYPE_SHOP);
    itemTable[BUY_BLUE_POTION]               = Item(false, false, &noVariable,              Text{"Buy Blue Potion",              "Acheter: Potion bleue",                           "Comprar poción azul"},                             BUY_BLUE_POTION,              (u32)GetItemID::GI_POTION_BLUE,             ITEMTYPE_SHOP);
    itemTable[BUY_HEROS_SHIELD]              = Item(false, false, &noVariable,              Text{"Buy Hero's Shield",            "Acheter: Bouclier du Héros",                      "Comprar escudo del héroe"},                        BUY_HEROS_SHIELD,             (u32)GetItemID::GI_SHIELD_HERO,             ITEMTYPE_SHOP);
    itemTable[BUY_BOMBCHU_10]                = Item(false, false, &noVariable,              Text{"Buy Bombchu (10)",             "Acheter: Missiles Teigneux (10)",                 "Comprar bombchus (10)"},                           BUY_BOMBCHU_10,               (u32)GetItemID::GI_BOMBCHUS_10,             ITEMTYPE_SHOP);
    itemTable[SOLD_OUT]                      = Item(false, false, &noVariable,              Text{"Sold Out",                     "Vendu",                                           "Vendido"},                                         SOLD_OUT,                     (u32)GetItemID::GI_NONE,                    ITEMTYPE_SHOP);
    itemTable[BUY_FAIRYS_SPIRIT]             = Item(false, false, &noVariable,              Text{"Buy Fairy's Spirit",           "Acheter: Fée",                                    "Comprar hada"},                                    BUY_FAIRYS_SPIRIT,            (u32)GetItemID::GI_FAIRY,                   ITEMTYPE_SHOP);
    itemTable[BUY_MAGIC_BEAN]                = Item(false, false, &noVariable,              Text{"Buy Magic Bean",               "Acheter: Haricot Magique",                        "Comprar habichuela mágica"},                       BUY_MAGIC_BEAN,               (u32)GetItemID::GI_MAGIC_BEAN,              ITEMTYPE_SHOP);
//Progressive Items
    itemTable[PROGRESSIVE_SWORD]             = Item(true,  false, &ProgressiveSword,        Text{"Progressive Sword",            "Lame (prog.)",                                    "Espada progresiva"},                               PROGRESSIVE_SWORD,            0x4A,                                       ITEMTYPE_ITEM);
    itemTable[PROGRESSIVE_BOMB_BAG]          = Item(true,  false, &ProgressiveBombBag,      Text{"Progressive Bomb Bag",         "Sac de bombes (prog.)",                           "Saco de bombas progresivo"},                       PROGRESSIVE_BOMB_BAG,         0x46,                                       ITEMTYPE_ITEM);
    itemTable[PROGRESSIVE_BOW]               = Item(true,  false, &ProgressiveBow,          Text{"Progressive Bow",              "Arc (prog.)",                                     "Arco progresivo"},                                 PROGRESSIVE_BOW,              0x47,                                       ITEMTYPE_ITEM);
    itemTable[PROGRESSIVE_WALLET]            = Item(true,  false, &ProgressiveWallet,       Text{"Progressive Wallet",           "Bourse (prog.)",                                  "Bolsa de rupias progresiva"},                      PROGRESSIVE_WALLET,           0x48,                                       ITEMTYPE_ITEM);
    itemTable[PROGRESSIVE_MAGIC_METER]       = Item(true,  false, &ProgressiveMagic,        Text{"Progressive Magic Meter",      "Énergie magique (prog.)",                         "Poder mágico progresivo"},                         PROGRESSIVE_MAGIC_METER,      0x49,                                       ITEMTYPE_GFAIRY);

    itemTable[MAJORAS_MASK]                  = Item(true,  false, &noVariable,              Text{"Majora's Mask",                "Masque de Majora",                                "Máscara de Majora"},                               MAJORAS_MASK,                 (u32)GetItemID::GI_ERROR_NOTHING_40,        ITEMTYPE_EVENT);
    itemTable[HINT]                          = Item(true,  true,  &noVariable,              Text{"Hint",                         "Indice",                                          "Pista"},                                           HINT,                         (u32)GetItemID::GI_ERROR_NOTHING_40,        ITEMTYPE_EVENT);

  //itemTable[PROGRESSIVE_BOMBCHUS]          = Item(true,  false, &Bombchus,                Text{"",                             "",                                                ""},                                                PROGRESSIVE_BOMBCHUS,         0x89,                                       ITEMTYPE_ITEM);
  //itemTable[PROGRESSIVE_NUT_UPGRADE]       = Item(false, false, &noVariable,              Text{"",                             "",                                                ""},                                                PROGRESSIVE_NUT_UPGRADE,      0x87,                                       ITEMTYPE_ITEM);
  //itemTable[PROGRESSIVE_STICK_UPGRADE]     = Item(false, false, &noVariable,              Text{"",                             "",                                                ""},                                                PROGRESSIVE_STICK_UPGRADE,    0x88,                                       ITEMTYPE_ITEM);


};

Item& ItemTable(const ItemKey itemKey) {
    return itemTable[itemKey];
};

//This function should only be used to place items containing hint text
//at gossip stone locations
void NewItem(const ItemKey itemKey, const Item item) {
    if (itemKey <= PROGRESSIVE_MAGIC_METER) {
        printf("\x1b[25;0HWARNING: ATTEMPTED TO OVERWRITE ITEM %lu\n", itemKey);
        return;
    }
    itemTable[itemKey] = item;
}
